# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a3e78053b4c06fa6d91989eec179aaab250ab3b45ba6a4f0ed656ac5395333034e13a2bdeeada630144ce9683c2d2dd3296f47ebfaedbe5468bad99bcbfee8c

test:
  secret_key_base: 294b779d4dd94a575043252c09421770899af641ec5e7f1471727be68cdc3856ad73681cdd4507ab34d287db2b74186921d8d1f4185d5a5fb3779e913b66ad15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
